# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3705323fa07fb02875d5b40ca71fd861"
name = "gift-registry-guru"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_customers,read_files,read_inventory,read_locales,read_orders,read_product_listings,read_themes,write_content,write_files,write_inventory,write_locales,write_orders,write_products,write_themes"

[auth]
redirect_urls = [
    "https://example.com/api/auth",
    "https://example.com/auth/callback",
    "https://example.com/auth/shopify/callback",
    "https://example.com/api/auth/callback"
]

[app_proxy]
url = "https://example.com/wfGiftRegistry"
subpath = "wf-gift-registry"
prefix = "apps"


[pos]
embedded = false